export const MAKE_TRANSACTION_REQUEST = 'MAKE_TRANSACTION_REQUEST'
export const MAKE_TRANSACTION_SUCCESS = 'MAKE_TRANSACTION_SUCCESS'
export const MAKE_TRANSACTION_FAIL = 'MAKE_TRANSACTION_FAIL'


export const TRANSACTIONS_LIST_REQUEST = 'TRANSACTIONS_LIST_REQUEST'
export const TRANSACTIONS_LIST_SUCCESS = 'TRANSACTIONS_LIST_SUCCESS'
export const TRANSACTIONS_LIST_FAIL = 'TRANSACTIONS_LIST_FAIL'